using Avalonia.Input;
using ParentElement.RichText.Core.Input;

namespace ParentElement.RichText.Avalonia.Platform;

internal static class Statics
{
    /// <summary>
    /// Maps Avalonia <see cref="Key"/> values to their platform-agnostic <see cref="KeyCode"/>
    /// equivalents. Used by <see cref="AvaloniaExtensions.ToKeyCode"/>.
    /// </summary>
    public static readonly Dictionary<Key, KeyCode> KeyConversionMap = new Dictionary<Key, KeyCode>
    {
        { Key.A, KeyCode.A },
        { Key.B, KeyCode.B },
        { Key.C, KeyCode.C },
        { Key.D, KeyCode.D },
        { Key.E, KeyCode.E },
        { Key.F, KeyCode.F },
        { Key.G, KeyCode.G },
        { Key.H, KeyCode.H },
        { Key.I, KeyCode.I },
        { Key.J, KeyCode.J },
        { Key.K, KeyCode.K },
        { Key.L, KeyCode.L },
        { Key.M, KeyCode.M },
        { Key.N, KeyCode.N },
        { Key.O, KeyCode.O },
        { Key.P, KeyCode.P },
        { Key.Q, KeyCode.Q },
        { Key.R, KeyCode.R },
        { Key.S, KeyCode.S },
        { Key.T, KeyCode.T },
        { Key.U, KeyCode.U },
        { Key.V, KeyCode.V },
        { Key.W, KeyCode.W },
        { Key.X, KeyCode.X },
        { Key.Y, KeyCode.Y },
        { Key.Z, KeyCode.Z },
        { Key.D0, KeyCode.D0 },
        { Key.D1, KeyCode.D1 },
        { Key.D2, KeyCode.D2 },
        { Key.D3, KeyCode.D3 },
        { Key.D4, KeyCode.D4 },
        { Key.D5, KeyCode.D5 },
        { Key.D6, KeyCode.D6 },
        { Key.D7, KeyCode.D7 },
        { Key.D8, KeyCode.D8 },
        { Key.D9, KeyCode.D9 },
        { Key.NumPad0, KeyCode.NumPad0 },
        { Key.NumPad1, KeyCode.NumPad1 },
        { Key.NumPad2, KeyCode.NumPad2 },
        { Key.NumPad3, KeyCode.NumPad3 },
        { Key.NumPad4, KeyCode.NumPad4 },
        { Key.NumPad5, KeyCode.NumPad5 },
        { Key.NumPad6, KeyCode.NumPad6 },
        { Key.NumPad7, KeyCode.NumPad7 },
        { Key.NumPad8, KeyCode.NumPad8 },
        { Key.NumPad9, KeyCode.NumPad9 },
        { Key.F1, KeyCode.F1 },
        { Key.F2, KeyCode.F2 },
        { Key.F3, KeyCode.F3 },
        { Key.F4, KeyCode.F4 },
        { Key.F5, KeyCode.F5 },
        { Key.F6, KeyCode.F6 },
        { Key.F7, KeyCode.F7 },
        { Key.F8, KeyCode.F8 },
        { Key.F9, KeyCode.F9 },
        { Key.F10, KeyCode.F10 },
        { Key.F11, KeyCode.F11 },
        { Key.F12, KeyCode.F12 },
        { Key.F13, KeyCode.F13 },
        { Key.F14, KeyCode.F14 },
        { Key.F15, KeyCode.F15 },
        { Key.F16, KeyCode.F16 },
        { Key.F17, KeyCode.F17 },
        { Key.F18, KeyCode.F18 },
        { Key.F19, KeyCode.F19 },
        { Key.F20, KeyCode.F20 },
        { Key.F21, KeyCode.F21 },
        { Key.F22, KeyCode.F22 },
        { Key.F23, KeyCode.F23 },
        { Key.F24, KeyCode.F24 },
        { Key.OemComma, KeyCode.OemComma },
        { Key.OemPeriod, KeyCode.OemPeriod },
        { Key.OemQuestion, KeyCode.OemQuestion },
        { Key.OemPlus, KeyCode.OemPlus },
        { Key.OemMinus, KeyCode.OemMinus },
        { Key.OemTilde, KeyCode.OemTilde },
        { Key.OemOpenBrackets, KeyCode.OemOpenBrackets },
        { Key.OemCloseBrackets, KeyCode.OemCloseBrackets },
        { Key.OemPipe, KeyCode.OemPipe },
        { Key.OemQuotes, KeyCode.OemQuotes },
        { Key.OemSemicolon, KeyCode.OemSemicolon },
        { Key.OemBackslash, KeyCode.OemBackslash },
        { Key.LeftCtrl, KeyCode.LControlKey },
        { Key.RightCtrl, KeyCode.RControlKey },
        { Key.LeftShift, KeyCode.LShiftKey },
        { Key.RightShift, KeyCode.RShiftKey },
        { Key.Divide, KeyCode.Divide },
        { Key.Multiply, KeyCode.Multiply },
        { Key.Add, KeyCode.Add },
        { Key.Subtract, KeyCode.Subtract },
        { Key.Return, KeyCode.Enter },
        { Key.Separator, KeyCode.Separator },
        { Key.Insert, KeyCode.Insert },
        { Key.Delete, KeyCode.Delete },
        { Key.Space, KeyCode.Space },
        { Key.PageUp, KeyCode.PageUp },
        { Key.PageDown, KeyCode.PageDown },
        { Key.End, KeyCode.End },
        { Key.Home, KeyCode.Home },
        { Key.Back, KeyCode.Back },
        { Key.Tab, KeyCode.Tab },
        { Key.Left, KeyCode.Left },
        { Key.Right, KeyCode.Right },
        { Key.Up, KeyCode.Up },
        { Key.Down, KeyCode.Down }
    };

}
